### ISSUE TITLE
plugin breaks  configuration settings page

### ISSUE THREAD

**Issue by niklasw** [jean-michel-gonet/dokuwiki-plugin-latexport#36]
The php fatal error is:
`Cannot declare class decorator, because the name is already in use in /.../latexport/renderer/decorator.php`

latexport git rev: a785db52f341644d443c16a4be613dd8dadaa58a
dokuwiki git rev: 1121b972bffbf7afb0aef5dfb54f8857c73c3c56

**Comment by jean-michel-gonet** [comment]
I'm sorry but I'm unable to reproduce this problem. I tried the following, using stable _Release 2018-04-22b "Greebo"_

1. Log out and log in as administrator.
2. Go to **Admin**
3. Click on **Configuration Settings**
4. Change anything that looks innocuous, like the _tagline_
5. Save.
6. Put back the original value.
7. Save.

And I could not see any error.

Please, reopen the bug if you have more information.

**Comment by lprobsth** [comment]
@jean-michel-gonet 

I get the same error when installing the latexport plugin and I'm running Release 2018-04-22b "Greebo".

Currently I'm not able to set up a testing environment (I only have a working unit).

My current unit comes with the following (non standard) plugins:

- caption
- Dw2Pdf
- Flowchartjs
- include
- TocTweak ver.2
- Wrap

I've tried to deactivate these plugins for a short period of time (no uninstallation due to a working unit with frequent visits by users) - but the behavior didn't change.
